@host = http://localhost:5050

### root
GET {{host}}

### get all users (not defined in user controller)
GET {{host}}/user

### register
POST {{host}}/user/register
Content-Type: application/json

{
  "name": "Sam Seifu",
  "username": "samseifu",
  "email": "sam@seifu.com",
  "password": "Password1",
  "passwordCheck": "Password1"
}

### log in
POST {{host}}/user/login
Content-Type: application/json

{
  "username": "simazon",
  "password": "Password1"
}

### update (not defined in user controller yet)
PUT {{host}}/user/update/63c4f562fdec9de1fe31fdb9 
Content-Type: application/json

{
"email": "sima@zon.dom",
"cart": [
  {
    "id": "5f5f5f5f5f5f5f5f5f5f5f5f",
    "quantity": 1
  },
  {
    "id": "5f5f67676767676767676767",
    "quantity": 1
  }],
  "orders": [
  {
    "id": "5f5f5f5f5f5f5f5f5f5f5f5f",
    "quantity": 1,
    "status": "pending"
  },
  {
    "id": "5f5f67676767676767676767",
    "quantity": 1,
    "status": "delivered"
  }],
  "paymentinfo": {
    "type": "creditcard",
    "cardnumber": "1234567890123456",
    "expirationdate": "2020-12-31",
    "securitycode": "123"
  }
}

### delete user (not defined in user controller yet)
DELETE {{host}}/user/63c5ec460d5f63b62af4949c