@host = http://localhost:5050

###
GET {{host}}

###
GET {{host}}/product

###
POST {{host}}/product
Content-Type: application/json

{
  "name": "iPhone14",
  "category": "gadget",
  "image": "http://image/image.png",
  "price": 1000,
  "countInStock": 7,
  "brand": "Apple",
  "rating": 4,
  "numReviews": 3,
  "description": "This phone is blablabla"
}

### 
GET {{host}}/product/637f9c34cdeba786547e7b7e

### 
PUT {{host}}/product/637f9c34cdeba786547e7b7e 
Content-Type: application/json

{
  "name": "iPhone14 Pro",
  "category": "gadget",
  "image": "http://image/image/iphone14pro.png",
  "price": 1200,
  "countInStock": 5,
  "brand": "Apple",
  "rating": 4,
  "numReviews": 9,
  "description": "The pro version is ..."
}


###
DELETE {{host}}/product/637f9c34cdeba786547e7b7e