###
GET {{host}}

###
GET {{host}}/product

### get a product
GET {{host}}/product/6975b16bc8718c38629a1416

###
POST {{host}}/debug/admin-key
x-admin-key: {{adminKey}}

###
POST {{host}}/product
Content-Type: application/json
x-admin-key: {{adminKey}}

{
  "title": "my product3",
  "description": "my product description",
  "price": 110.00,
  "discountPercentage": 10,
  "rating": 5,
  "stock": 100,
  "brand": "my brand",
  "category": "my category",
  "thumbnail": "my thumbnail",
  "images": [
    "my image 1",
    "my image 2"
  ]
}

###
# delete (protected)
DELETE {{host}}/product/6975c540539c9fc89a538af6
x-admin-key: {{adminKey}}

{
  "title": "my product3",
  "description": "my product description",
  "price": 110.00,
  "discountPercentage": 10,
  "rating": 5,
  "stock": 100,
  "brand": "my brand",
  "category": "my category",
  "thumbnail": "my thumbnail",
  "images": [
    "my image 1",
    "my image 2"
  ]
}

### update a product
PUT {{host}}/product/63c5f00d85528a36cf5d754b
Content-Type: application/json

{
  "title": "my product",
  "description": "my product description",
  "price": 200.00,
  "discountPercentage": 10,
  "rating": 5,
  "stock": 100,
  "brand": "my brand",
  "category": "my category",
  "thumbnail": "my thumbnail",
  "images": [
    "my image 1",
    "my image 2"
  ]
}


### delete a product
DELETE {{host}}/product/63c5f00d85528a36cf5d754b


