@host = http://localhost:5050

###
GET {{host}}

###
GET {{host}}/item

###
POST {{host}}/item
Content-Type: application/json

{
  "title": "my product",
  "description": "my product description",
  "price": 100.00,
  "discountPercentage": 10,
  "rating": 5,
  "stock": 100,
  "brand": "my brand",
  "category": "my category",
  "thumbnail": "my thumbnail",
  "images": [
    "my image 1",
    "my image 2"
  ]
}

### get a product
GET {{host}}/item/63c5f00d85528a36cf5d754b

### update a product
PUT {{host}}/item/63c5f00d85528a36cf5d754b
Content-Type: application/json

{
  "title": "my product",
  "description": "my product description",
  "price": 200.00,
  "discountPercentage": 10,
  "rating": 5,
  "stock": 100,
  "brand": "my brand",
  "category": "my category",
  "thumbnail": "my thumbnail",
  "images": [
    "my image 1",
    "my image 2"
  ]
}

### delete a product
DELETE {{host}}/item/63c5f00d85528a36cf5d754b


