@host = http://localhost:5050

###
GET {{host}}

###
GET {{host}}/user/1



###
POST {{host}}/user/register
Content-Type: application/json

{
  "name": "Geni Abebe",
  "username": "geniabebe2",
  "email": "geni2@abebe.com",
  "password": "Password1"
}
###
GET {{host}}/user/profile

###  get user profile
GET {{host}}/user/profile
Content-Type: application/json

{
  "username": "simameng"
}

###
GET {{host}}/user/pro

### 
PUT {{host}}/user/637f95c98ba06bb588beea77 
Content-Type: application/json

{
"email": "changed@email.com"
}


### register
POST {{host}}/user/register
Content-Type: application/json

{
  "name": "Somebody Someone",
  "email": "somebody@someone.com",
  "password": "Password1",
  "passwordCheck": "Password1"
}


### log in
POST {{host}}/user/login
Content-Type: application/json

{
  "email": "sima@meng.com",
  "password": "pass"
}

### log out
POST {{host}}/user/logout
Content-Type: application/json

{
  "email": "sima@meng.com"
}

### delete user
DELETE {{host}}/user/638508871d9706d43b804eb1